// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jAkGcwlcgs84pfRoE50wGfFSp-AWkIE',
    appId: '1:647009775572:web:6025c0697699a3d94c3041',
    messagingSenderId: '647009775572',
    projectId: 'azok-8581b',
    authDomain: 'azok-8581b.firebaseapp.com',
    databaseURL: 'https://azok-8581b.firebaseio.com',
    storageBucket: 'azok-8581b.appspot.com',
    measurementId: 'G-7F48JPRHGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVg4BYvWAB5SqcAe_LwV95zc8DbStbbs',
    appId: '1:647009775572:android:483349a1f6fc618f4c3041',
    messagingSenderId: '647009775572',
    projectId: 'azok-8581b',
    databaseURL: 'https://azok-8581b.firebaseio.com',
    storageBucket: 'azok-8581b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5lk7mw1R8wOSN1zZEKSgJC3fdDLUaTo',
    appId: '1:647009775572:ios:936c01aec39085b74c3041',
    messagingSenderId: '647009775572',
    projectId: 'azok-8581b',
    databaseURL: 'https://azok-8581b.firebaseio.com',
    storageBucket: 'azok-8581b.appspot.com',
    iosClientId:
        '647009775572-l2mhb2ser39688b83bt0jlt2ql1bn6n1.apps.googleusercontent.com',
    iosBundleId: 'com.ozel.pets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5lk7mw1R8wOSN1zZEKSgJC3fdDLUaTo',
    appId: '1:647009775572:ios:936c01aec39085b74c3041',
    messagingSenderId: '647009775572',
    projectId: 'azok-8581b',
    databaseURL: 'https://azok-8581b.firebaseio.com',
    storageBucket: 'azok-8581b.appspot.com',
    iosClientId:
        '647009775572-l2mhb2ser39688b83bt0jlt2ql1bn6n1.apps.googleusercontent.com',
    iosBundleId: 'com.ozel.pets',
  );
}
